FROM amazoncorretto:21-alpine3.21-jdk AS builder

WORKDIR /app

COPY buildSrc ./buildSrc
COPY http ./http
COPY gradle ./gradle

COPY gradlew ./
COPY settings.gradle.kts ./
COPY gradle.properties ./

RUN ./gradlew installDist

FROM amazoncorretto:21-alpine3.21-jdk

WORKDIR /app

COPY --from=builder /app/http/build/ ./build

CMD ["./build/install/http/bin/http"]




